import '../models/agenda_data.dart';
import '../models/contact_data.dart';

AgendaData agenda = AgendaData(contacts: [
  ContactData(
      id: 1,
      name: "Carlos",
      surname: "Fernández",
      email: "carlos.fernandez@example.com",
      phone: "654-123-456",
      birthdate: DateTime(1985, 3, 14),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Trabajo", "Amigo"]),
  ContactData(
      id: 2,
      name: "María",
      surname: "Gómez",
      email: "maria.gomez@example.com",
      phone: "654-987-321",
      birthdate: DateTime(1990, 7, 25),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Familia"]),
  ContactData(
      id: 3,
      name: "Javier",
      surname: "López",
      email: "javier.lopez@example.com",
      phone: "645-765-432",
      birthdate: DateTime(1988, 1, 10),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Trabajo"]),
  ContactData(
      id: 4,
      name: "Ana",
      surname: "Martínez",
      email: "ana.martinez@example.com",
      phone: "678-555-789",
      birthdate: DateTime(1995, 5, 30),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Amigo"]),
  ContactData(
      id: 5,
      name: "Pablo",
      surname: "Sánchez",
      email: "pablo.sanchez@example.com",
      phone: "600-123-999",
      birthdate: DateTime(1983, 12, 4),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Familia", "Amigo"]),
  ContactData(
      id: 6,
      name: "Elena",
      surname: "Ruiz",
      email: "elena.ruiz@example.com",
      phone: "699-888-777",
      birthdate: DateTime(1998, 9, 15),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Trabajo"]),
  ContactData(
      id: 7,
      name: "Raúl",
      surname: "Hernández",
      email: "raul.hernandez@example.com",
      phone: "611-234-567",
      birthdate: DateTime(1980, 6, 20),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Amigo"]),
  ContactData(
      id: 8,
      name: "Lucía",
      surname: "Díaz",
      email: "lucia.diaz@example.com",
      phone: "644-765-123",
      birthdate: DateTime(1992, 8, 22),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Trabajo"]),
  ContactData(
      id: 9,
      name: "Diego",
      surname: "Molina",
      email: "diego.molina@example.com",
      phone: "600-333-222",
      birthdate: DateTime(1987, 10, 8),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Familia"]),
  ContactData(
      id: 10,
      name: "Isabel",
      surname: "Ortega",
      email: "isabel.ortega@example.com",
      phone: "633-999-555",
      birthdate: DateTime(1993, 4, 18),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Trabajo", "Amigo"]),
  ContactData(
      id: 11,
      name: "Fernando",
      surname: "Torres",
      email: "fernando.torres@example.com",
      phone: "655-111-777",
      birthdate: DateTime(1991, 11, 2),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Familia"]),
  ContactData(
      id: 12,
      name: "Sara",
      surname: "Ramos",
      email: "sara.ramos@example.com",
      phone: "620-444-666",
      birthdate: DateTime(1999, 2, 14),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Trabajo"]),
  ContactData(
      id: 13,
      name: "Manuel",
      surname: "García",
      email: "manuel.garcia@example.com",
      phone: "677-555-999",
      birthdate: DateTime(1986, 7, 7),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Familia"]),
  ContactData(
      id: 14,
      name: "Carmen",
      surname: "Vega",
      email: "carmen.vega@example.com",
      phone: "699-333-111",
      birthdate: DateTime(1984, 3, 29),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Amigo"]),
  ContactData(
      id: 15,
      name: "Antonio",
      surname: "Pérez",
      email: "antonio.perez@example.com",
      phone: "655-222-888",
      birthdate: DateTime(1989, 6, 17),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Trabajo"]),
  ContactData(
      id: 16,
      name: "Marta",
      surname: "Suárez",
      email: "marta.suarez@example.com",
      phone: "611-666-444",
      birthdate: DateTime(1994, 12, 9),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Familia"]),
  ContactData(
      id: 17,
      name: "José",
      surname: "Morales",
      email: "jose.morales@example.com",
      phone: "644-111-777",
      birthdate: DateTime(1981, 5, 5),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Amigo"]),
  ContactData(
      id: 18,
      name: "Eva",
      surname: "Castillo",
      email: "eva.castillo@example.com",
      phone: "677-444-222",
      birthdate: DateTime(1997, 9, 28),
      creation: DateTime.now(),
      modification: DateTime.now(),
      label: ["Trabajo"]),
  ContactData(
      id: 19,
      name: "Alejandro",
      surname: "Jiménez",
      email: "alejandro.jimenez@example.com",
      phone: "600-999-555",
      birthdate: DateTime(1982, 11, 14),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: false,
      label: ["Familia"]),
  ContactData(
      id: 20,
      name: "Laura",
      surname: "Navarro",
      email: "laura.navarro@example.com",
      phone: "699-222-888",
      birthdate: DateTime(1990, 1, 3),
      creation: DateTime.now(),
      modification: DateTime.now(),
      isFavorite: true,
      label: ["Amigo", "Trabajo"]),
]);
